sql_init = '''
CREATE TABLE IF NOT EXISTS ORDERS(
   ORDER_ID CHAR(20) NOT NULL,
   REQUESTED_PICKUP_TIME CHAR(50) NOT NULL,
   PICKUP_INSTRUCTIONS CHAR(255),
   DELIVERY_INSTRUCTIONS CHAR(255),
   PRIMARY KEY(ORDER_ID)
);

CREATE TABLE IF NOT EXISTS DELIVERY_ADDRESS(
   ORDER_ID CHAR(20) NOT NULL,
   UNIT CHAR(20) NOT NULL,
   STREET CHAR(50),
   SUBURB CHAR(50),
   CITY CHAR(255),
   POSTCODE CHAR(20),
   CONSTRAINT fk_order
    FOREIGN KEY(ORDER_ID)
        REFERENCES ORDERS(ORDER_ID)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PICKUP_ADDRESS(
   ORDER_ID CHAR(20) NOT NULL,
   UNIT CHAR(20) NOT NULL,
   STREET CHAR(50),
   SUBURB CHAR(50),
   CITY CHAR(255),
   POSTCODE CHAR(20),
   CONSTRAINT fk_order
    FOREIGN KEY(ORDER_ID)
        REFERENCES ORDERS(ORDER_ID)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ITEMS(
   ITEM_ID CHAR(20) NOT NULL,
   ORDER_ID CHAR(20) NOT NULL,
   QUANTITY CHAR(20),
   PRIMARY KEY(ITEM_ID),
   CONSTRAINT fk_order
    FOREIGN KEY(ORDER_ID)
        REFERENCES ORDERS(ORDER_ID)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TRIP(
   TRIP_ID CHAR(255) NOT NULL,
   TRIP_START CHAR(255) NOT NULL,
   TRIP_END CHAR(255),
   DISTANCE NUMERIC,
   FUEL NUMERIC,
   PLANNED_DATE DATE,
   CARRIER_CODE CHAR(255),
   PRIMARY KEY(TRIP_ID)
);

CREATE TABLE IF NOT EXISTS TRIP_ORDER_REF(
   TRIP_ID CHAR(255) NOT NULL,
   ORDER_ID CHAR(255) NOT NULL,
   CONSTRAINT fk_order
    FOREIGN KEY(ORDER_ID)
        REFERENCES ORDERS(ORDER_ID)
        ON DELETE CASCADE,
   CONSTRAINT fk_trip
    FOREIGN KEY(TRIP_ID)
        REFERENCES TRIP(TRIP_ID)
        ON DELETE CASCADE
);
'''

create_order_sql = '''
INSERT INTO ORDERS(ORDER_ID, REQUESTED_PICKUP_TIME, PICKUP_INSTRUCTIONS, DELIVERY_INSTRUCTIONS)
VALUES (%s,%s,%s,%s)
'''

create_delivery_address_sql = '''
INSERT INTO DELIVERY_ADDRESS(ORDER_ID, UNIT, STREET, SUBURB, CITY, POSTCODE)
VALUES (%s,%s,%s,%s,%s,%s)
'''

create_pickup_address_sql = '''
INSERT INTO PICKUP_ADDRESS(ORDER_ID, UNIT, STREET, SUBURB, CITY, POSTCODE)
VALUES (%s,%s,%s,%s,%s,%s)
'''

create_item_sql = '''
INSERT INTO ITEMS(ITEM_ID, ORDER_ID, QUANTITY)
VALUES (%s,%s,%s)
'''

create_trip_sql = '''
INSERT INTO TRIP(TRIP_ID, TRIP_START, TRIP_END, DISTANCE, FUEL, PLANNED_DATE, CARRIER_CODE)
VALUES (%s,%s,%s,%s,%s,%s,%s)
'''

create_trip_order_ref_sql = '''
INSERT INTO TRIP(TRIP_ID, ORDER_ID)
VALUES (%s,%s)
'''